-- ============================================================================
-- POLICYDEBATE101.COM — DATABASE SCHEMA v0.1
-- ----------------------------------------------------------------------------
-- Run in Supabase SQL editor.
-- Auth (auth.users) is managed by Supabase. We mirror an app-level profile.
-- ============================================================================

create extension if not exists "pgcrypto";

-- ---------- Profiles (mirrors auth.users) -----------------------------------

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null check (role in ('student','teacher','admin')) default 'student',
  display_name text not null,
  email text not null unique,
  avatar_config jsonb not null default '{}'::jsonb,
  credits integer not null default 0,
  rank_xp integer not null default 0,
  streak integer not null default 0,
  created_at timestamptz not null default now()
);

-- ---------- Classes ---------------------------------------------------------

create table if not exists public.classes (
  id uuid primary key default gen_random_uuid(),
  teacher_id uuid not null references public.profiles(id) on delete cascade,
  name text not null,                -- "Period 4 - 7th Grade" or "MS Novice"
  join_code text not null unique,    -- 6-char shareable code
  division text check (division is null or division in ('ms','hs')),   -- lab division
  level    text check (level    is null or level    in ('novice','jv','varsity')),
  created_at timestamptz not null default now()
);

create index if not exists idx_classes_teacher on public.classes(teacher_id);

-- ---------- Class coaches (many-to-many) ------------------------------------
-- A lab can have multiple coaches. Membership grants full teacher-level
-- access to the class via is_class_teacher(). Equal status; no head/assistant
-- distinction (deferred until we actually need it).
create table if not exists public.class_coaches (
  class_id uuid not null references public.classes(id)   on delete cascade,
  coach_id uuid not null references public.profiles(id) on delete cascade,
  added_at timestamptz not null default now(),
  added_by uuid references public.profiles(id) on delete set null,
  primary key (class_id, coach_id)
);

create index if not exists idx_class_coaches_coach on public.class_coaches(coach_id);

-- ---------- Coach invite tokens (magic-link onboarding) ---------------------
-- Generated by admins on /coach/invites, claimed by coaches via /coach/join.
-- On claim: profile promoted to teacher + class_coaches row inserted.
create table if not exists public.coach_invite_tokens (
  token       text primary key,
  class_id    uuid not null references public.classes(id) on delete cascade,
  email       text,
  note        text,
  created_by  uuid references public.profiles(id) on delete set null,
  created_at  timestamptz not null default now(),
  expires_at  timestamptz not null,
  used_at     timestamptz,
  used_by     uuid references public.profiles(id) on delete set null
);

create index if not exists idx_coach_invite_tokens_class on public.coach_invite_tokens(class_id);
create index if not exists idx_coach_invite_tokens_open
  on public.coach_invite_tokens(expires_at)
  where used_at is null;

-- ---------- Enrollments -----------------------------------------------------

create table if not exists public.enrollments (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  student_id uuid not null references public.profiles(id) on delete cascade,
  joined_at timestamptz not null default now(),
  unique(class_id, student_id)
);

create index if not exists idx_enrollments_student on public.enrollments(student_id);
create index if not exists idx_enrollments_class on public.enrollments(class_id);

-- ---------- Missions (catalog) ----------------------------------------------
-- The actual content lives in JSON files in the repo. This table is the catalog
-- the teacher dashboard reads when assigning. Keep in sync with /content/missions/.

create table if not exists public.missions (
  id text primary key,                 -- "inherency-v1" — matches JSON file
  campaign_id text not null,
  sector_id text not null,
  number integer not null,
  title text not null,
  subtitle text,
  difficulty text not null,
  estimated_minutes integer not null,
  prerequisites text[] not null default '{}',
  unlocks text[] not null default '{}',
  active boolean not null default true
);

-- ---------- Assignments -----------------------------------------------------

create table if not exists public.assignments (
  id uuid primary key default gen_random_uuid(),
  class_id uuid not null references public.classes(id) on delete cascade,
  mission_id text not null references public.missions(id),
  assigned_at timestamptz not null default now(),
  due_at timestamptz,
  required boolean not null default true,
  unique(class_id, mission_id)
);

create index if not exists idx_assignments_class on public.assignments(class_id);

-- ---------- Attempts (every CFU answer) -------------------------------------

create table if not exists public.attempts (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  mission_id text not null references public.missions(id),
  slide_id text not null,
  type text not null,                  -- "cfu-mcq" etc.
  correct boolean not null,
  details jsonb not null,              -- shape varies by type, see mission-schema.ts
  started_at timestamptz not null,
  submitted_at timestamptz not null default now(),
  time_spent_ms integer not null
);

create index if not exists idx_attempts_student_mission on public.attempts(student_id, mission_id);
create index if not exists idx_attempts_class_mission on public.attempts(class_id, mission_id);
create index if not exists idx_attempts_mission_slide on public.attempts(mission_id, slide_id);

-- ---------- Completions (one per student per mission) -----------------------

create table if not exists public.completions (
  id uuid primary key default gen_random_uuid(),
  student_id uuid not null references public.profiles(id) on delete cascade,
  class_id uuid not null references public.classes(id) on delete cascade,
  mission_id text not null references public.missions(id),
  finished_at timestamptz not null default now(),
  credits_earned integer not null,
  accuracy numeric(4,3) not null,      -- 0.000–1.000
  shields_remaining integer not null,
  unique(student_id, mission_id)
);

create index if not exists idx_completions_class_mission on public.completions(class_id, mission_id);

-- ============================================================================
-- ROW LEVEL SECURITY
-- ============================================================================

alter table public.profiles           enable row level security;
alter table public.classes            enable row level security;
alter table public.class_coaches      enable row level security;
alter table public.coach_invite_tokens enable row level security;
alter table public.enrollments        enable row level security;
alter table public.missions           enable row level security;
alter table public.assignments        enable row level security;
alter table public.attempts           enable row level security;
alter table public.completions        enable row level security;

-- Helper functions for cross-table RLS checks. SECURITY DEFINER runs these as
-- the table owner, which is exempt from RLS by default — this is required
-- here because classes' and enrollments' SELECT policies each query the
-- other table; inlining those joins directly in the policy (instead of going
-- through one of these RLS-bypassing helpers) causes infinite recursion
-- (Postgres error 42P17) the moment either table is read.
-- See supabase/migrations/2026-06-24_fix_rls_recursion.sql.

-- Multi-coach aware: true if the caller owns the class OR is listed in
-- class_coaches. See 2026-07-07_labs_and_coach_invites.sql.
create or replace function public.is_class_teacher(p_class_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.classes
    where id = p_class_id and teacher_id = auth.uid()
  )
  or exists (
    select 1 from public.class_coaches
    where class_id = p_class_id and coach_id = auth.uid()
  );
$$;

create or replace function public.is_enrolled_in_class(p_class_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.enrollments where class_id = p_class_id and student_id = auth.uid()
  );
$$;

create or replace function public.is_teacher_of_student(p_student_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.enrollments e
    join public.classes c on c.id = e.class_id
    where e.student_id = p_student_id and c.teacher_id = auth.uid()
  );
$$;

grant execute on function public.is_class_teacher(uuid)      to authenticated;
grant execute on function public.is_enrolled_in_class(uuid)  to authenticated;
grant execute on function public.is_teacher_of_student(uuid) to authenticated;

-- profiles: read own, teachers read students in their classes, admin all
create policy "own profile read"   on public.profiles for select using (auth.uid() = id);
create policy "own profile update" on public.profiles for update using (auth.uid() = id);
create policy "teacher reads class profiles" on public.profiles for select
  using (public.is_teacher_of_student(profiles.id));

-- classes: teachers see their own classes, students see classes they're in
create policy "teacher owns classes" on public.classes for all using (teacher_id = auth.uid());
create policy "student reads enrolled classes" on public.classes for select
  using (public.is_enrolled_in_class(classes.id));

-- class_coaches: coaches see their own membership rows. Writes are admin-only
-- (the invite-claim flow uses the service-role admin client to bypass RLS).
create policy "coach reads own class_coaches" on public.class_coaches for select
  using (coach_id = auth.uid());
create policy "admin writes class_coaches" on public.class_coaches for all
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- coach_invite_tokens: admin-only (both reads and writes).
create policy "admin reads coach_invite_tokens" on public.coach_invite_tokens for select
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));
create policy "admin writes coach_invite_tokens" on public.coach_invite_tokens for all
  using (exists (select 1 from public.profiles where id = auth.uid() and role = 'admin'));

-- enrollments: student sees their own, teacher sees their classes'
create policy "student reads own enrollments" on public.enrollments for select using (student_id = auth.uid());
create policy "teacher reads class enrollments" on public.enrollments for select
  using (public.is_class_teacher(enrollments.class_id));
create policy "student joins class" on public.enrollments for insert with check (student_id = auth.uid());
create policy "teacher removes student" on public.enrollments for delete
  using (public.is_class_teacher(enrollments.class_id));

-- missions: anyone signed in can read the catalog
create policy "anyone reads missions" on public.missions for select using (auth.uid() is not null);

-- assignments: students see their class's, teachers manage their class's
create policy "student reads class assignments" on public.assignments for select
  using (public.is_enrolled_in_class(assignments.class_id));
create policy "teacher manages assignments" on public.assignments for all
  using (public.is_class_teacher(assignments.class_id));

-- attempts: students write their own, read their own; teachers read their class's
create policy "student writes own attempts" on public.attempts for insert with check (student_id = auth.uid());
create policy "student reads own attempts" on public.attempts for select using (student_id = auth.uid());
create policy "teacher reads class attempts" on public.attempts for select
  using (public.is_class_teacher(attempts.class_id));

-- completions: same pattern
create policy "student writes own completions" on public.completions for insert with check (student_id = auth.uid());
create policy "student reads own completions" on public.completions for select using (student_id = auth.uid());
create policy "teacher reads class completions" on public.completions for select
  using (public.is_class_teacher(completions.class_id));
