-- ============================================================================
-- 2026-06-24 — PIN auth for students, password auth for teachers
-- ----------------------------------------------------------------------------
-- We're moving off Google OAuth entirely.
--
-- Strategy (Path 2 — synthetic email + Supabase Auth):
--   • Students get a synthetic email like `marcus-j.cdsi-2026-a@cdsi.local`
--     and a 4-digit PIN as their Supabase Auth password.
--   • Teachers use real email + password (Supabase Auth email/password flow).
--   • All existing RLS keeps working because auth.uid() still resolves.
--
-- This migration only adds *app-level metadata* (pin_set, lockout, class
-- bootstrap). The actual auth credentials live in auth.users (managed by
-- Supabase Auth) and we never touch them directly except via the admin API.
-- ============================================================================

-- ---------- profiles: add columns for PIN flow ------------------------------

alter table public.profiles
  add column if not exists pin_set boolean not null default false,
  add column if not exists pin_failed_attempts integer not null default 0,
  add column if not exists pin_locked_at timestamptz,
  add column if not exists primary_class_id uuid references public.classes(id) on delete set null;

comment on column public.profiles.pin_set is
  'TRUE once the student has chosen their PIN (first login flow complete).';
comment on column public.profiles.pin_failed_attempts is
  'Consecutive wrong PIN attempts. Reset to 0 on success. Locked at 5.';
comment on column public.profiles.pin_locked_at is
  'When student was locked out (5 wrong PINs). NULL = not locked.';
comment on column public.profiles.primary_class_id is
  'Which class the student logs in under. Drives the class-code → roster flow.';

-- ---------- classes: ensure short, human-typeable join codes ----------------
-- Existing schema allows any unique text. We don't change existing codes,
-- but new ones generated by the server action will follow CDSI-2026-A pattern.

-- ---------- RLS additions ---------------------------------------------------
-- Students need to be able to read the names of OTHER students in their class
-- during the login flow (so they can pick their name from a grid). But the
-- login flow runs BEFORE the student has auth.uid() — they haven't signed in
-- yet. So the roster-fetch must use the service-role key (server action only).
--
-- We don't open new client-readable policies. Server actions using the admin
-- client bypass RLS for the login bootstrap.

-- ---------- teacher_invite_codes (optional, not used in v1) ------------------
-- Future: teachers can self-register with an invite code. Not built yet.

-- ---------- helper: generate a join code ------------------------------------

create or replace function public.generate_join_code()
returns text
language plpgsql
as $$
declare
  candidate text;
  attempts int := 0;
begin
  loop
    -- 6-char alphanumeric, no ambiguous chars (no 0/O, 1/I/L)
    candidate := upper(
      substr(
        translate(encode(gen_random_bytes(8), 'base64'), '/+=OIL01', ''),
        1, 6
      )
    );
    exit when length(candidate) = 6 and not exists (
      select 1 from public.classes where join_code = candidate
    );
    attempts := attempts + 1;
    if attempts > 50 then
      raise exception 'Could not generate unique join code after 50 attempts';
    end if;
  end loop;
  return candidate;
end;
$$;
